### ISSUE TITLE
1 Gastnutzer: 1.1 Als Gastnutzer möchte ich die verfügbaren Hotels durchsuchen, damit ich dasjenige auswählen kann, welches meinen Wünschen entspricht.

### ISSUE THREAD

**Issue by RobinJHaag** [s0pple/Gruppe_F#8]
- [x] 1.1.1. Ich möchte alle Hotels in einer Stadt durchsuchen, damit ich das Hotel nach meinem bevorzugten Standort (Stadt) auswählen kann. (OG)
- [x] 1.1.2. Ich möchte alle Hotels in einer Stadt nach der Anzahl der Sterne durchsuchen.(pn)
- [x] 1.1.3. Ich möchte alle Hotels in einer Stadt durchsuchen, die Zimmer haben, die meiner Gästezahl entsprechen (nur 1 Zimmer pro Buchung), entweder mit oder ohne Anzahl der Sterne. (OG)
- [x] 1.1.4. Ich möchte alle Hotels in einer Stadt durchsuchen, die während meines Aufenthaltes ("von" (start_date) und "bis" (end_date)) Zimmer für meine Gästezahl zur Verfügung haben, entweder mit oder ohne Anzahl der Sterne, damit ich nur relevante Ergebnisse sehe. (PN)
- [x] 1.1.5. Ich möchte die folgenden Informationen pro Hotel sehen: Name, Adresse, Anzahl der Sterne. (OG)
- [ ] 1.1.6. Ich möchte ein Hotel auswählen, um die Details zu sehen (z.B.verfügbare Zimmer [siehe 1.2])  (PN)
- [ ] Alles in UI konvertieren

**Comment by s0pple** [comment]
[Dokumentation_27.05.2024_User-Storie;1.1.5._OG.docx](https://github.com/s0pple/Gruppe_F/files/15456275/Dokumentation_27.05.2024_User-Storie.1.1.5._OG.docx)
